name: Example workflow
on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
permissions: read-all

jobs:
  latest-version:
    name: Latest version
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'windows-latest', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: install_kit
        with:
          version: 'latest'

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_kit.outputs }}"

      - name: Run kit tools
        shell: bash
        run: |
          set -x
          kit version

  known-version:
    name: Known version
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'windows-latest', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: install_kit
        with:
          version: 'v0.1.0'

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_kit.outputs }}"

      - name: Run installed tools
        shell: bash
        run: |
          set -x
          kit version
